//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HMPROJECT
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T уровень заряда.
    /// </summary>
    // *** Start programmer edit section *** (tУровеньЗаряда CustomAttributes)

    // *** End programmer edit section *** (tУровеньЗаряда CustomAttributes)
    public enum tУровеньЗаряда
    {
        
        // *** Start programmer edit section *** (tУровеньЗаряда.Высокий CustomAttributes)

        // *** End programmer edit section *** (tУровеньЗаряда.Высокий CustomAttributes)
        Высокий,
        
        // *** Start programmer edit section *** (tУровеньЗаряда.Средний CustomAttributes)

        // *** End programmer edit section *** (tУровеньЗаряда.Средний CustomAttributes)
        Средний,
        
        // *** Start programmer edit section *** (tУровеньЗаряда.Низкий CustomAttributes)

        // *** End programmer edit section *** (tУровеньЗаряда.Низкий CustomAttributes)
        Низкий,
    }
}
