//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HMPROJECT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Здание CustomAttributes)

    // *** End programmer edit section *** (Здание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданиеE", new string[] {
            "Адрес as \'Адрес\'",
            "Улица as \'Улица\'",
            "Человек as \'Человек\'",
            "Человек.Номер as \'Номер\'"}, Hidden=new string[] {
            "Человек.Номер"})]
    [MasterViewDefineAttribute("ЗданиеE", "Человек", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ЗданиеL", new string[] {
            "Адрес as \'Адрес\'",
            "Улица as \'Улица\'",
            "Человек.Номер as \'Номер\'"})]
    public class Здание : ICSSoft.STORMNET.DataObject
    {
        
        private int fАдрес;
        
        private string fУлица;
        
        private IIS.HMPROJECT.Человек fЧеловек;
        
        // *** Start programmer edit section *** (Здание CustomMembers)

        // *** End programmer edit section *** (Здание CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Адрес CustomAttributes)

        // *** End programmer edit section *** (Здание.Адрес CustomAttributes)
        public virtual int Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Адрес Get start)

                // *** End programmer edit section *** (Здание.Адрес Get start)
                int result = this.fАдрес;
                // *** Start programmer edit section *** (Здание.Адрес Get end)

                // *** End programmer edit section *** (Здание.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Адрес Set start)

                // *** End programmer edit section *** (Здание.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Здание.Адрес Set end)

                // *** End programmer edit section *** (Здание.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Улица.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Улица CustomAttributes)

        // *** End programmer edit section *** (Здание.Улица CustomAttributes)
        [StrLen(255)]
        public virtual string Улица
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Улица Get start)

                // *** End programmer edit section *** (Здание.Улица Get start)
                string result = this.fУлица;
                // *** Start programmer edit section *** (Здание.Улица Get end)

                // *** End programmer edit section *** (Здание.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Улица Set start)

                // *** End programmer edit section *** (Здание.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (Здание.Улица Set end)

                // *** End programmer edit section *** (Здание.Улица Set end)
            }
        }
        
        /// <summary>
        /// Здание.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Человек CustomAttributes)

        // *** End programmer edit section *** (Здание.Человек CustomAttributes)
        [PropertyStorage(new string[] {
                "Человек"})]
        [NotNull()]
        public virtual IIS.HMPROJECT.Человек Человек
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Человек Get start)

                // *** End programmer edit section *** (Здание.Человек Get start)
                IIS.HMPROJECT.Человек result = this.fЧеловек;
                // *** Start programmer edit section *** (Здание.Человек Get end)

                // *** End programmer edit section *** (Здание.Человек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Человек Set start)

                // *** End programmer edit section *** (Здание.Человек Set start)
                this.fЧеловек = value;
                // *** Start programmer edit section *** (Здание.Человек Set end)

                // *** End programmer edit section *** (Здание.Человек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.HMPROJECT.Здание));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.HMPROJECT.Здание));
                }
            }
        }
    }
}
