//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HMPROJECT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приборы зд.
    /// </summary>
    // *** Start programmer edit section *** (ПриборыЗд CustomAttributes)

    // *** End programmer edit section *** (ПриборыЗд CustomAttributes)
    [AutoAltered()]
    [Caption("Приборы зд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриборыЗдE", new string[] {
            "Номер as \'Номер\'",
            "Ммакс as \'Ммакс\'",
            "Ммин as \'Ммин\'",
            "Тмакс as \'Тмакс\'",
            "Тмин as \'Тмин\'",
            "Пмакс as \'Пмакс\'",
            "Пмин as \'Пмин\'",
            "УровеньЗаряда as \'Уровень заряда\'",
            "Здание as \'Здание\'",
            "Здание.Улица as \'Улица\'"}, Hidden=new string[] {
            "Здание.Улица"})]
    [MasterViewDefineAttribute("ПриборыЗдE", "Здание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Улица")]
    [View("ПриборыЗдL", new string[] {
            "Номер as \'Номер\'",
            "Ммакс as \'Ммакс\'",
            "Ммин as \'Ммин\'",
            "Тмакс as \'Тмакс\'",
            "Тмин as \'Тмин\'",
            "Пмакс as \'Пмакс\'",
            "Пмин as \'Пмин\'",
            "УровеньЗаряда as \'Уровень заряда\'",
            "Здание.Улица as \'Улица\'"})]
    public class ПриборыЗд : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private double fМмакс;
        
        private double fМмин;
        
        private double fТмакс;
        
        private double fТмин;
        
        private double fПмакс;
        
        private double fПмин;
        
        private IIS.HMPROJECT.tУровеньЗаряда fУровеньЗаряда;
        
        private IIS.HMPROJECT.Здание fЗдание;
        
        // *** Start programmer edit section *** (ПриборыЗд CustomMembers)

        // *** End programmer edit section *** (ПриборыЗд CustomMembers)

        
        /// <summary>
        /// Ммакс.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Ммакс CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Ммакс CustomAttributes)
        public virtual double Ммакс
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Ммакс Get start)

                // *** End programmer edit section *** (ПриборыЗд.Ммакс Get start)
                double result = this.fМмакс;
                // *** Start programmer edit section *** (ПриборыЗд.Ммакс Get end)

                // *** End programmer edit section *** (ПриборыЗд.Ммакс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Ммакс Set start)

                // *** End programmer edit section *** (ПриборыЗд.Ммакс Set start)
                this.fМмакс = value;
                // *** Start programmer edit section *** (ПриборыЗд.Ммакс Set end)

                // *** End programmer edit section *** (ПриборыЗд.Ммакс Set end)
            }
        }
        
        /// <summary>
        /// Ммин.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Ммин CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Ммин CustomAttributes)
        public virtual double Ммин
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Ммин Get start)

                // *** End programmer edit section *** (ПриборыЗд.Ммин Get start)
                double result = this.fМмин;
                // *** Start programmer edit section *** (ПриборыЗд.Ммин Get end)

                // *** End programmer edit section *** (ПриборыЗд.Ммин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Ммин Set start)

                // *** End programmer edit section *** (ПриборыЗд.Ммин Set start)
                this.fМмин = value;
                // *** Start programmer edit section *** (ПриборыЗд.Ммин Set end)

                // *** End programmer edit section *** (ПриборыЗд.Ммин Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Номер CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Номер Get start)

                // *** End programmer edit section *** (ПриборыЗд.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПриборыЗд.Номер Get end)

                // *** End programmer edit section *** (ПриборыЗд.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Номер Set start)

                // *** End programmer edit section *** (ПриборыЗд.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПриборыЗд.Номер Set end)

                // *** End programmer edit section *** (ПриборыЗд.Номер Set end)
            }
        }
        
        /// <summary>
        /// Пмакс.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Пмакс CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Пмакс CustomAttributes)
        public virtual double Пмакс
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Пмакс Get start)

                // *** End programmer edit section *** (ПриборыЗд.Пмакс Get start)
                double result = this.fПмакс;
                // *** Start programmer edit section *** (ПриборыЗд.Пмакс Get end)

                // *** End programmer edit section *** (ПриборыЗд.Пмакс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Пмакс Set start)

                // *** End programmer edit section *** (ПриборыЗд.Пмакс Set start)
                this.fПмакс = value;
                // *** Start programmer edit section *** (ПриборыЗд.Пмакс Set end)

                // *** End programmer edit section *** (ПриборыЗд.Пмакс Set end)
            }
        }
        
        /// <summary>
        /// Пмин.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Пмин CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Пмин CustomAttributes)
        public virtual double Пмин
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Пмин Get start)

                // *** End programmer edit section *** (ПриборыЗд.Пмин Get start)
                double result = this.fПмин;
                // *** Start programmer edit section *** (ПриборыЗд.Пмин Get end)

                // *** End programmer edit section *** (ПриборыЗд.Пмин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Пмин Set start)

                // *** End programmer edit section *** (ПриборыЗд.Пмин Set start)
                this.fПмин = value;
                // *** Start programmer edit section *** (ПриборыЗд.Пмин Set end)

                // *** End programmer edit section *** (ПриборыЗд.Пмин Set end)
            }
        }
        
        /// <summary>
        /// Тмакс.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Тмакс CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Тмакс CustomAttributes)
        public virtual double Тмакс
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Тмакс Get start)

                // *** End programmer edit section *** (ПриборыЗд.Тмакс Get start)
                double result = this.fТмакс;
                // *** Start programmer edit section *** (ПриборыЗд.Тмакс Get end)

                // *** End programmer edit section *** (ПриборыЗд.Тмакс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Тмакс Set start)

                // *** End programmer edit section *** (ПриборыЗд.Тмакс Set start)
                this.fТмакс = value;
                // *** Start programmer edit section *** (ПриборыЗд.Тмакс Set end)

                // *** End programmer edit section *** (ПриборыЗд.Тмакс Set end)
            }
        }
        
        /// <summary>
        /// Тмин.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Тмин CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Тмин CustomAttributes)
        public virtual double Тмин
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Тмин Get start)

                // *** End programmer edit section *** (ПриборыЗд.Тмин Get start)
                double result = this.fТмин;
                // *** Start programmer edit section *** (ПриборыЗд.Тмин Get end)

                // *** End programmer edit section *** (ПриборыЗд.Тмин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Тмин Set start)

                // *** End programmer edit section *** (ПриборыЗд.Тмин Set start)
                this.fТмин = value;
                // *** Start programmer edit section *** (ПриборыЗд.Тмин Set end)

                // *** End programmer edit section *** (ПриборыЗд.Тмин Set end)
            }
        }
        
        /// <summary>
        /// УровеньЗаряда.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.УровеньЗаряда CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.УровеньЗаряда CustomAttributes)
        public virtual IIS.HMPROJECT.tУровеньЗаряда УровеньЗаряда
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.УровеньЗаряда Get start)

                // *** End programmer edit section *** (ПриборыЗд.УровеньЗаряда Get start)
                IIS.HMPROJECT.tУровеньЗаряда result = this.fУровеньЗаряда;
                // *** Start programmer edit section *** (ПриборыЗд.УровеньЗаряда Get end)

                // *** End programmer edit section *** (ПриборыЗд.УровеньЗаряда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.УровеньЗаряда Set start)

                // *** End programmer edit section *** (ПриборыЗд.УровеньЗаряда Set start)
                this.fУровеньЗаряда = value;
                // *** Start programmer edit section *** (ПриборыЗд.УровеньЗаряда Set end)

                // *** End programmer edit section *** (ПриборыЗд.УровеньЗаряда Set end)
            }
        }
        
        /// <summary>
        /// Приборы зд.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Здание CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.HMPROJECT.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Здание Get start)

                // *** End programmer edit section *** (ПриборыЗд.Здание Get start)
                IIS.HMPROJECT.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (ПриборыЗд.Здание Get end)

                // *** End programmer edit section *** (ПриборыЗд.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Здание Set start)

                // *** End programmer edit section *** (ПриборыЗд.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (ПриборыЗд.Здание Set end)

                // *** End programmer edit section *** (ПриборыЗд.Здание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриборыЗдE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборыЗдE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборыЗдE", typeof(IIS.HMPROJECT.ПриборыЗд));
                }
            }
            
            /// <summary>
            /// "ПриборыЗдL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборыЗдL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборыЗдL", typeof(IIS.HMPROJECT.ПриборыЗд));
                }
            }
        }
    }
}
