//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HMPROJECT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прибор учета.
    /// </summary>
    // *** Start programmer edit section *** (ПриборУчета CustomAttributes)

    // *** End programmer edit section *** (ПриборУчета CustomAttributes)
    [AutoAltered()]
    [Caption("Прибор учета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриборУчетаE", new string[] {
            "Номер as \'Номер\'",
            "Название as \'Название\'",
            "ПриборыЗд as \'Приборы зд\'",
            "ПриборыЗд.Номер as \'Номер\'"}, Hidden=new string[] {
            "ПриборыЗд.Номер"})]
    [MasterViewDefineAttribute("ПриборУчетаE", "ПриборыЗд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ПриборУчетаL", new string[] {
            "Номер as \'Номер\'",
            "Название as \'Название\'",
            "ПриборыЗд.Номер as \'Номер\'"})]
    public class ПриборУчета : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНазвание;
        
        private IIS.HMPROJECT.ПриборыЗд fПриборыЗд;
        
        // *** Start programmer edit section *** (ПриборУчета CustomMembers)

        // *** End programmer edit section *** (ПриборУчета CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчета.Название CustomAttributes)

        // *** End programmer edit section *** (ПриборУчета.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчета.Название Get start)

                // *** End programmer edit section *** (ПриборУчета.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ПриборУчета.Название Get end)

                // *** End programmer edit section *** (ПриборУчета.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчета.Название Set start)

                // *** End programmer edit section *** (ПриборУчета.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ПриборУчета.Название Set end)

                // *** End programmer edit section *** (ПриборУчета.Название Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчета.Номер CustomAttributes)

        // *** End programmer edit section *** (ПриборУчета.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчета.Номер Get start)

                // *** End programmer edit section *** (ПриборУчета.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПриборУчета.Номер Get end)

                // *** End programmer edit section *** (ПриборУчета.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчета.Номер Set start)

                // *** End programmer edit section *** (ПриборУчета.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПриборУчета.Номер Set end)

                // *** End programmer edit section *** (ПриборУчета.Номер Set end)
            }
        }
        
        /// <summary>
        /// Прибор учета.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчета.ПриборыЗд CustomAttributes)

        // *** End programmer edit section *** (ПриборУчета.ПриборыЗд CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриборыЗд"})]
        [NotNull()]
        public virtual IIS.HMPROJECT.ПриборыЗд ПриборыЗд
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчета.ПриборыЗд Get start)

                // *** End programmer edit section *** (ПриборУчета.ПриборыЗд Get start)
                IIS.HMPROJECT.ПриборыЗд result = this.fПриборыЗд;
                // *** Start programmer edit section *** (ПриборУчета.ПриборыЗд Get end)

                // *** End programmer edit section *** (ПриборУчета.ПриборыЗд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчета.ПриборыЗд Set start)

                // *** End programmer edit section *** (ПриборУчета.ПриборыЗд Set start)
                this.fПриборыЗд = value;
                // *** Start programmer edit section *** (ПриборУчета.ПриборыЗд Set end)

                // *** End programmer edit section *** (ПриборУчета.ПриборыЗд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриборУчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчетаE", typeof(IIS.HMPROJECT.ПриборУчета));
                }
            }
            
            /// <summary>
            /// "ПриборУчетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчетаL", typeof(IIS.HMPROJECT.ПриборУчета));
                }
            }
        }
    }
}
