//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HMPROJECT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Человек.
    /// </summary>
    // *** Start programmer edit section *** (Человек CustomAttributes)

    // *** End programmer edit section *** (Человек CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧеловекE", new string[] {
            "Номер as \'Номер\'"})]
    [View("ЧеловекL", new string[] {
            "Номер as \'Номер\'"})]
    public class Человек : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        // *** Start programmer edit section *** (Человек CustomMembers)

        // *** End programmer edit section *** (Человек CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Человек.Номер CustomAttributes)

        // *** End programmer edit section *** (Человек.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Человек.Номер Get start)

                // *** End programmer edit section *** (Человек.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Человек.Номер Get end)

                // *** End programmer edit section *** (Человек.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Человек.Номер Set start)

                // *** End programmer edit section *** (Человек.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Человек.Номер Set end)

                // *** End programmer edit section *** (Человек.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧеловекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекE", typeof(IIS.HMPROJECT.Человек));
                }
            }
            
            /// <summary>
            /// "ЧеловекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекL", typeof(IIS.HMPROJECT.Человек));
                }
            }
        }
    }
}
